# Generated by Django 5.0.4 on 2024-05-03 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mailing_name_alter_mailing_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 16, 32, 52, 415388, tzinfo=datetime.timezone.utc), verbose_name='дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 16, 32, 52, 415388, tzinfo=datetime.timezone.utc), verbose_name='дата и время начала'),
        ),
    ]
