# Generated by Django 5.0.4 on 2024-05-03 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_mailing_clients_alter_mailing_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 17, 0, 35, 338981, tzinfo=datetime.timezone.utc), verbose_name='дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('День', 'day'), ('Неделя', 'week'), ('Месяц', 'month')], default='day', max_length=30, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 17, 0, 35, 338981, tzinfo=datetime.timezone.utc), verbose_name='дата и время начала'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создана', 'created'), ('Выполняется', 'ongoing'), ('Завершена', 'finished')], default='created', max_length=30, verbose_name='статус рассылки'),
        ),
    ]
