# Generated by Django 5.0.4 on 2024-05-03 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_mailing_finish_alter_mailing_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 18, 49, 52, 913851, tzinfo=datetime.timezone.utc), verbose_name='дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 18, 49, 52, 913851, tzinfo=datetime.timezone.utc), verbose_name='дата и время начала'),
        ),
    ]
