# Generated by Django 5.0.4 on 2024-05-03 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_client_owner_mailing_owner_message_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 22, 45, 31, 834889, tzinfo=datetime.timezone.utc), verbose_name='дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 22, 45, 31, 834889, tzinfo=datetime.timezone.utc), verbose_name='дата и время начала'),
        ),
    ]
