# Generated by Django 5.0.4 on 2024-05-03 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_mailing_next_sending_time_try_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 23, 53, 0, 490495, tzinfo=datetime.timezone.utc), verbose_name='дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 23, 53, 0, 490495, tzinfo=datetime.timezone.utc), verbose_name='дата и время начала'),
        ),
    ]
